/**
 * @file pantry.schema.ts
 * @description HomeOS — Pantry & Shopping Module Schemas
 * SPEC Reference: SPEC-001 §4.3–4.4, SPEC-006
 */

import { z } from 'zod';
import { BaseEntitySchema, UUIDSchema, UTCDateTimeSchema } from './core.schema.js';

// ─────────────────────────────────────────────────────────────────────────────
// SHARED ENUMS (SPEC-001 §4.3.1–4.3.2)
// ─────────────────────────────────────────────────────────────────────────────

export const UOMSchema = z.enum(['pcs', 'kg', 'g', 'L', 'ml', 'lbs', 'oz', 'box', 'bag']);
export type UOM = z.infer<typeof UOMSchema>;

export const LocationSchema = z.enum(['Fridge', 'Freezer', 'Pantry', 'Garage', 'Other']);
export type Location = z.infer<typeof LocationSchema>;

// ─────────────────────────────────────────────────────────────────────────────
// PANTRY ITEM
// conflictResolutionStrategy: last-write-wins
// Stale quantity is self-correcting at next physical use.
// Negative quantity is blocked by SPEC-006 Rule 1 (clamped to 0).
// ─────────────────────────────────────────────────────────────────────────────

export const PantryItemSchema = BaseEntitySchema.extend({
  name: z.string().min(1).max(100),
  quantity: z.number().min(0)
    .describe('Clamped to 0 by validator; never negative. SPEC-006 Rule 1.'),
  unit: UOMSchema,
  location: LocationSchema.default('Pantry'),
  parLevel: z.number().min(0).default(1)
    .describe('Reorder trigger point. When quantity <= parLevel, a ShoppingListItem is auto-created. SPEC-006 Rule 2.'),
  expiryDate: UTCDateTimeSchema.optional(),
  barcode: z.string().optional()
    .describe('EAN-13 or UPC-A. Stored but not externally looked up in v1.'),
  lastPurchasedAt: UTCDateTimeSchema.optional()
    .describe('Updated by Finance validator when a linked Transaction is written. SPEC-005 Rule 4.'),
  averageCost: z.number().min(0).optional()
    .describe('Running average price. Recalculated by Finance validator. SPEC-005 Rule 4.'),
  conflictResolutionStrategy: z.literal('last-write-wins').default('last-write-wins'),
});

export type PantryItem = z.infer<typeof PantryItemSchema>;

// ─────────────────────────────────────────────────────────────────────────────
// SHOPPING LIST ITEM
// conflictResolutionStrategy: last-write-wins
// Two people buying the same item simultaneously is safe — quantity merges naturally.
// ─────────────────────────────────────────────────────────────────────────────

export const ShoppingListItemSchema = BaseEntitySchema.extend({
  name: z.string().min(1).max(100)
    .describe('May differ from PantryItem.name (e.g. brand name). Display label only.'),
  quantity: z.number().positive(),
  unit: UOMSchema,
  sourcePantryItemId: UUIDSchema.optional()
    .describe('Set when auto-generated by parLevel trigger (SPEC-006 Rule 2). createdBy = SYSTEM_MEMBER_ID in that case.'),
  status: z.enum(['needed', 'purchased', 'discarded']).default('needed'),
  store: z.string().max(50).optional()
    .describe('Optional store preference e.g. "Costco"'),
  estimatedCost: z.number().min(0).optional(),
  conflictResolutionStrategy: z.literal('last-write-wins').default('last-write-wins'),
});

export type ShoppingListItem = z.infer<typeof ShoppingListItemSchema>;

// ─────────────────────────────────────────────────────────────────────────────
// ERROR CODES (SPEC-006)
// ─────────────────────────────────────────────────────────────────────────────

export const PantryErrorCodes = {
  NEGATIVE_QUANTITY:       'PANTRY_NEGATIVE_QUANTITY',
  UNIT_CHANGE_RESETS_QTY: 'PANTRY_UNIT_CHANGE_RESETS_QTY',
  LINKED_TRANSACTION:     'PANTRY_LINKED_TRANSACTION',
} as const;
